name: s1335_clock_radio 
description: "S-1335 clock radio"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # SVG rendering
  flutter_svg: any
  # Audio
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  media_kit_native_event_loop: ^1.0.9
  # Persist settings
  shared_preferences: ^2.2.3
  # Non-white loading screen when loading app on all platforms
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/led_segments/
    - assets/sounds/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_native_splash:
  color: "#000000"